version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mdapi-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./php.ini:/usr/local/etc/php/php.ini
    ports:
      - "9000:9000"
    networks:
      - mdapi-network

  webserver:
    image: nginx:latest
    container_name: mdapi-nginx
    restart: unless-stopped
    ports:
      - "8044:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - mdapi-network

  mysql:
    image: mysql:8.0
    container_name: mdapi-mysql
    restart: unless-stopped
    ports:
      - "3312:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mdapi
      MYSQL_USER: mdapi_user
      MYSQL_PASSWORD: mdapi_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mdapi-network

networks:
  mdapi-network:
    driver: bridge

volumes:
  mysql_data:
